apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accounts
    spec:
      containers:
      - image: us.icr.io/sn-labs-apoorvpatil2/accounts:1
        name: accounts
        resources: {}
        # -----------------------------------------------
        # START OF REQUIRED EDITS FOR STEP 6.4 (EXERCISE 7)
        # -----------------------------------------------
        env:
        - name: DATABASE_HOST
          value: postgresql
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-name
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-password
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-user
status: {}
